# Generated by Django 6.0.3 on 2026-04-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
