# Generated by Django 6.0.3 on 2026-05-05 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_employee_role_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allowed_month_end',
            field=models.IntegerField(blank=True, help_text='Last month (1-12) this leave window closes. Leave blank to restrict to the start month only.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='allowed_month',
            field=models.IntegerField(blank=True, help_text='First month (1-12) this leave is available from. Leave blank for year-round availability.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
