# Generated by Django 6.0.3 on 2026-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leavetype_allowed_month_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='allowed_month',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='allowed_month_end',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allowed_months',
            field=models.JSONField(blank=True, default=None, help_text='List of months (1–12) when this leave may be taken. e.g. [1, 6, 12] means January, June, and December. Leave null/empty for year-round availability.', null=True),
        ),
    ]
